language: python
python:
  - "3.6" # current default Python on Travis CI
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - coverage run -m unittest discover -v

after_success:
  - bash <(curl -s https://codecov.io/bash)
